/**/twist_mux:
  ros__parameters:
    topics:
      keyboard:
        topic   : wolf_controller/keyboard
        timeout : 2.0
        priority: 2
      twist:
        topic   : wolf_controller/twist
        timeout : 2.0
        priority: 1
    locks:
      e_stop:
        topic   : e_stop
        timeout : 0.0
        priority: 255
